---
title: "testforbarchart"
author: "Lucy Lin"
date: "11/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("barchart.R")
```

## R Markdown

This is the barchart

```{r weapons, fig.width=14, fig.height=8}
library(ggplot2)
weapon_barchart <- ggplot(top10_weapons) + 
  geom_col(mapping = aes(x= Weapon, y = Weapon_Incidents, fill = Weapon))+
  labs(title = "Top 10 Weapons in the US used for Homocide", 
       x = "Weapon Name",
       y = "Number of Homocide Incidents Caused by Weapon")+
  theme(text=element_text(size=17))
weapon_barchart

```

```{r US_incident}
library(ggplot2)
US_Incidents <- homocide_data %>% group_by(Year) %>% summarise(sumIncidents = sum(Incident))
NumIncidents_scatterplot <- ggplot(US_Incidents) +
  geom_point(mapping = aes(x= Year, y = sumIncidents)) +
  geom_line(mapping = aes(x= Year, y = sumIncidents)) +
  labs(title = "Number of Homocide Incidents in the US over the years, 1980 - 2014", 
       x = "Year",
       y = "Number of Homocide Incidents")+
  theme(text=element_text(size=12))
NumIncidents_scatterplot

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
